spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: none
  datasource:
    url: 'jdbc:mysql://localhost:3306/db_example'
    username: root
    password: root
    hikari:
      validationTimeout: 5000

org:
  jobrunr:
    background-job-server:
      enabled: true
#    job-scheduler:
#      enabled: true
    dashboard:
      enabled: true
      port: '8000'

